### ISSUE TITLE
radxa-zero-v20210930

### ISSUE THREAD

**Issue by microcyb** [radxa/radxa-zero-images-released#1]
zero_debian_buster_xfce4_arm64_20210930_1138-msdos.img are devoid of option to get WiFi state active.
nmcli general status shows the STATE as disconnected.  Image does not allow to connect.

**Comment by jack-ma** [comment]
@microcyb  Hi, thanks for the report. Which model of Zero do you test the image?

**Comment by microcyb** [comment]
1GB external model

**Comment by microcyb** [comment]
Solution..
https://github.com/armbian/firmware/tree/master/brcm

files
brcmfmac43430-sdio.bin
brcmfmac43430-sdio.txt

copy to lib/firmware/brcm

**Comment by StephenInVamrs** [comment]
Thanks. We have added these two files in the release, https://github.com/radxa/radxa-zero-images-released/releases/tag/radxa-zero-v20211010.
