### ISSUE TITLE
fe.dai-link-0: ASoC: no backend DAIs enabled for fe.dai-link-0

### ISSUE THREAD

**Issue by thieri** [radxa/radxa-zero-images-released#4]
using: zero_debian_buster_xfce4_arm64_20211010_0810-mbr.img
with: Radxa Zero 1GB ram (AP6212 module)

dmesg gives multiple of 
fe.dai-link-0: ASoC: no backend DAIs enabled for fe.dai-link-0

**Comment by dev-radxa** [comment]
This error is fixed. Please use the latest system image. 

https://github.com/radxa/radxa-zero-images-released/releases/tag/radxa-zero-v20211122

**Comment by StephenInVamrs** [comment]
The issue is fixed. Please use the latest images.

https://github.com/radxa/radxa-zero-images-released/releases/tag/radxa-zero-v20211122

**Comment by thieri** [comment]
Seems fixed in radxa-zero-v20211122

Thanks
